
const PlanetList = [
  {
    id: 255,
    name: "Sun",
    image: "/sun.gif",
    menu_image: "/sun_menu.jpg",
    details: {
    //   type: "Star",
      about: `The Sun is a nearly perfect sphere of hot plasma and the central star of our Solar System, accounting for about 99.8% of its total mass. Its immense gravitational pull keeps the planets, asteroids, and comets in orbit. The Sun primarily consists of hydrogen (about 74%) and helium (about 24%), undergoing nuclear fusion in its core to produce energy. This process converts hydrogen into helium, releasing enormous amounts of heat and light. The Sun’s surface temperature is around 5,500°C, while its core reaches about 15 million°C. Its magnetic field drives solar activity such as sunspots, solar flares, and coronal mass ejections, which can influence space weather and affect technology on Earth. Light from the Sun takes about 8 minutes to reach Earth. The Sun is classified as a G-type main-sequence star (G2V) and is about 4.6 billion years old. It is expected to remain stable for another 5 billion years before expanding into a red giant and eventually becoming a white dwarf. The Sun is the ultimate source of energy for life on Earth, driving climate, weather, and photosynthesis, making it essential for the existence of ecosystems and human civilization.`
    },
  },
  {
    id: 1,
    name: "Mercury",
    image: "/mercury.jpg",
    menu_image: "/mercury_menu.jpg",
    details: {
      aphelion: "69,816,900 km (0.4667 AU)",
      perihelion: "46,001,200 km (0.3075 AU)",
      semiMajorAxis: "57,909,100 km (0.387 AU)",
      eccentricity: "0.2056",
      orbitalPeriod: "87.97 days",
      synodicPeriod: "115.88 days",
      averageSpeed: "47.36 km/s",
      meanAnomaly: "174.796°",
      longitudeOfAscendingNode: "48.331°",
      argumentOfPerihelion: "29.124°",
      satellites: "None",
      about: `Mercury is the closest planet to the Sun and the smallest planet in the Solar System, with a diameter of about 4,880 km. It orbits the Sun once every 88 Earth days, making its year the shortest of all planets. Because Mercury has almost no atmosphere to trap heat, surface temperatures vary drastically: it can reach up to 430°C during the day and plummet to -180°C at night. Its surface resembles that of the Moon, covered with craters, ridges, and plains shaped by billions of years of impacts. Mercury’s core makes up about 85% of its radius, which is unusually large compared to other planets, suggesting a history of massive collisions. Despite its small size, Mercury has a global magnetic field, though it is only about 1% as strong as Earth’s. The planet has been visited by spacecraft such as Mariner 10 and MESSENGER, revealing details of its geology and thin exosphere composed of atoms blasted from its surface by solar wind. Because of its closeness to the Sun, Mercury is often difficult to observe from Earth, appearing only just before sunrise or just after sunset. Its extreme environment provides valuable insight into planetary formation and evolution.`
    },
  },
//   {
//     id: 2,
//     name: "Venus",
//     image: "/venus.jpg",
//     menu_image: "/venus_menu.jpg",
//     details: {
//       aphelion: "108,939,000 km (0.728 AU)",
//       perihelion: "107,477,000 km (0.718 AU)",
//       semiMajorAxis: "108,208,000 km (0.723 AU)",
//       eccentricity: "0.0067",
//       orbitalPeriod: "224.70 days",
//       synodicPeriod: "583.92 days",
//       averageSpeed: "35.02 km/s",
//       meanAnomaly: "50.115°",
//       longitudeOfAscendingNode: "76.680°",
//       argumentOfPerihelion: "54.884°",
//       satellites: "None",
//       about: `Venus is the second planet from the Sun and Earth’s closest planetary neighbor, often referred to as Earth’s “twin” because of their similar size, mass, and composition. Despite these similarities, Venus has an extremely hostile environment. Its thick atmosphere, made of 96% carbon dioxide, creates a runaway greenhouse effect, trapping heat and raising surface temperatures to around 465°C, hotter than Mercury despite being farther from the Sun. The atmospheric pressure on Venus is about 92 times that of Earth, equivalent to being nearly a kilometer underwater. Clouds of sulfuric acid cover the planet, reflecting sunlight and making Venus one of the brightest objects in the night sky. The surface is rocky, with vast plains, mountains, and thousands of volcanoes, some of which may still be active. Unlike most planets, Venus rotates very slowly and in the opposite direction to its orbit, resulting in a day that lasts longer than a Venusian year (243 Earth days vs. 225 Earth days). Venus has no natural satellites. Spacecraft like Magellan and Venus Express have mapped its surface and studied its atmosphere. Venus serves as a cautionary example of how climate and atmospheric conditions can dramatically shape a planet’s habitability.`
//     },
//   },
//   {
//     id:3,
//     name: "Earth",
//     image: "/earth.jpg",
//     menu_image: "/earth_menu.jpg",
//     details: {
//       aphelion: "152,100,000 km (1.017 AU)",
//       perihelion: "147,095,000 km (0.983 AU)",
//       semiMajorAxis: "149,598,000 km (1 AU)",
//       eccentricity: "0.0167",
//       orbitalPeriod: "365.25 days",
//       synodicPeriod: "— (reference point)",
//       averageSpeed: "29.78 km/s",
//       meanAnomaly: "357.517°",
//       longitudeOfAscendingNode: "348.739°",
//       argumentOfPerihelion: "114.207°",
//       satellites: "1 (Moon)",
//       about: `Earth is the third planet from the Sun and the only known world to support life. With a diameter of about 12,742 km, Earth is the fifth-largest planet in the Solar System. About 71% of its surface is covered by oceans, while the remaining 29% consists of continents and islands. Earth’s atmosphere is composed mainly of nitrogen and oxygen, providing breathable air and protecting life from harmful solar radiation. Its magnetic field, generated by the liquid outer core, shields the planet from solar wind. Earth has a moderate climate due to its distance from the Sun, axial tilt, and water cycle, which together sustain diverse ecosystems. The planet has one natural satellite, the Moon, which stabilizes Earth’s axial tilt and drives tides. Geological processes such as plate tectonics continuously reshape its surface. Earth’s biosphere has evolved for billions of years, producing millions of species of plants, animals, and microorganisms. Human civilization, emerging only in the last 10,000 years, has profoundly altered the planet through agriculture, technology, and industry. While Earth remains habitable, issues such as climate change, deforestation, and pollution pose challenges for the future. Its unique balance of conditions makes Earth a rare and remarkable planet.`
//     },
//   },
// {
  
//   id: 4,
//   name: "Mars",
//   image: "/mars.jpg",
//   menu_image: "/mars_menu.jpg",
//   details: {
//     aphelion: "249,200,000 km (1.666 AU)",
//     perihelion: "206,700,000 km (1.382 AU)",
//     semiMajorAxis: "227,939,200 km (1.524 AU)",
//     eccentricity: "0.0934",
//     orbitalPeriod: "686.98 days",
//     synodicPeriod: "779.94 days",
//     averageSpeed: "24.077 km/s",
//     meanAnomaly: "19.41°",
//     longitudeOfAscendingNode: "49.558°",
//     argumentOfPerihelion: "286.502°",
//     satellites: "Phobos, Deimos",
//     about: `Mars is the fourth planet from the Sun and is often called the “Red Planet” because of its reddish appearance caused by iron oxide on its surface. With a diameter of about 6,792 km, Mars is roughly half the size of Earth but has similar land features, including mountains, valleys, and polar ice caps. Mars is home to Olympus Mons, the tallest volcano in the Solar System, and Valles Marineris, a canyon system so vast it dwarfs the Grand Canyon. The planet has a thin atmosphere, composed mostly of carbon dioxide, which is unable to retain heat, causing extreme temperature variations. Temperatures range from around 20°C in daytime to –125°C at night. Mars has seasons like Earth due to its axial tilt. Its two small moons, Phobos and Deimos, are likely captured asteroids. Over the years, orbiters, landers, and rovers have revealed evidence of ancient river valleys, lake beds, and minerals that form in water, suggesting Mars once had a wetter and potentially habitable past. Today, exploration missions such as NASA’s Perseverance rover continue to study its geology, search for signs of past life, and test technologies for potential human missions in the future.`
//   },
// },
// {
//   id: 5,
//     name: "Jupiter",
//   image: "/jupiter.jpg",
//   menu_image: "/jupiter_menu.jpg",
//   details: {
//     aphelion: "816,620,000 km (5.458 AU)",
//     perihelion: "740,520,000 km (4.950 AU)",
//     semiMajorAxis: "778,570,000 km (5.203 AU)",
//     eccentricity: "0.0489",
//     orbitalPeriod: "11.86 years",
//     synodicPeriod: "398.88 days",
//     averageSpeed: "13.07 km/s",
//     meanAnomaly: "20.020°",
//     longitudeOfAscendingNode: "100.464°",
//     argumentOfPerihelion: "273.867°",
//     satellites: "95 (incl. Io, Europa, Ganymede, Callisto)",
//     about: `Jupiter is the largest planet in the Solar System, a gas giant with a diameter of about 142,984 km. It has a mass more than twice that of all the other planets combined. Jupiter is best known for its colorful cloud bands and the Great Red Spot, a massive storm larger than Earth that has raged for centuries. Its atmosphere is mostly hydrogen and helium, with ammonia clouds and violent weather patterns driven by fast rotation—it completes one day in just under 10 hours. Jupiter emits more heat than it receives from the Sun, due to slow gravitational contraction. The planet has a strong magnetic field and an enormous magnetosphere that extends millions of kilometers into space. Jupiter is orbited by a vast system of moons, the largest being the Galilean moons: Io, Europa, Ganymede, and Callisto. Each of these moons is unique—Europa may harbor a subsurface ocean, while Io is volcanically active. Jupiter also has faint rings composed of dust particles. Because of its size, composition, and influence, Jupiter is sometimes called the “vacuum cleaner” of the Solar System, as its gravity deflects comets and asteroids. Studying Jupiter provides insights into gas giant formation and the early Solar System.`
//   },
// },
// {
//   id: 6,
//   name: "Saturn",
//   image: "/saturn.jpg",
//   menu_image: "/saturn_menu.jpg",
//   details: {
//     aphelion: "1,513,325,783 km (10.123 AU)",
//     perihelion: "1,353,572,956 km (9.041 AU)",
//     semiMajorAxis: "1,433,529,000 km (9.582 AU)",
//     eccentricity: "0.0565",
//     orbitalPeriod: "29.46 years",
//     synodicPeriod: "378.09 days",
//     averageSpeed: "9.68 km/s",
//     meanAnomaly: "317.020°",
//     longitudeOfAscendingNode: "113.665°",
//     argumentOfPerihelion: "339.392°",
//     satellites: "146 (incl. Titan, Enceladus, Rhea)",
//     about: `Saturn is the sixth planet from the Sun and the second largest in the Solar System, with a diameter of 120,536 km. It is a gas giant composed mainly of hydrogen and helium, similar to Jupiter, but what makes Saturn most iconic are its spectacular rings. These rings are made up of countless particles of ice and rock ranging in size from tiny grains to large boulders. The planet itself has a very low density—so low, in fact, that it would float if placed in a giant cosmic ocean. Saturn rotates rapidly, completing one day in just 10.7 hours, causing it to flatten at the poles. It has a strong magnetic field and a complex atmosphere with fast-moving winds, storms, and long-lived features like the hexagonal storm at its north pole. Saturn has an extensive moon system, with Titan being the largest. Titan is larger than Mercury and has a thick atmosphere with lakes and rivers of liquid methane and ethane, making it a key target for exploration. Enceladus, another moon, has geysers that eject water vapor, hinting at a subsurface ocean. Saturn’s beauty and complexity continue to captivate scientists and astronomers, making it one of the most studied planets.`
//   },
// },
// {
//   id: 7,
//   name: "Uranus",
//   image: "/uranus.jpg",
//   menu_image: "/uranus_menu.jpg",
//   details: {
//     aphelion: "3,004,419,704 km (20.11 AU)",
//     perihelion: "2,742,610,658 km (18.33 AU)",
//     semiMajorAxis: "2,873,550,000 km (19.19 AU)",
//     eccentricity: "0.0472",
//     orbitalPeriod: "84.01 years",
//     synodicPeriod: "369.66 days",
//     averageSpeed: "6.80 km/s",
//     meanAnomaly: "142.238°",
//     longitudeOfAscendingNode: "74.006°",
//     argumentOfPerihelion: "96.998°",
//     satellites: "27 (incl. Titania, Oberon, Miranda)",
//     about: `Uranus is the seventh planet from the Sun and the third largest by diameter, measuring about 50,724 km across. Often called an “ice giant,” Uranus is composed mainly of hydrogen and helium, but it also contains a higher proportion of ices such as water, ammonia, and methane compared to Jupiter and Saturn. Methane in its upper atmosphere absorbs red light and reflects blue and green, giving the planet its striking bluish color. Uranus is unique because it rotates on its side, with an axial tilt of about 98 degrees. This unusual tilt likely resulted from a massive collision early in its history, and it causes extreme seasonal variations. Uranus has a very cold atmosphere, with temperatures dropping to –224°C, making it one of the coldest planets in the Solar System. It has a faint ring system and 27 known moons, including Titania, Oberon, and Miranda. These moons show diverse geological features, with some having evidence of past activity. Because Uranus has only been visited once, by Voyager 2 in 1986, much about it remains a mystery. Future missions could reveal more about its atmosphere, interior, and moons, offering clues about the formation of ice giants.`
//   },
// },
// {
//   id: 8,
//   name: "Neptune",
//   image: "/neptune.jpg",
//   menu_image: "/neptune_menu.jpg",
//   details: {
//     aphelion: "4,537,039,826 km (30.33 AU)",
//     perihelion: "4,459,753,056 km (29.81 AU)",
//     semiMajorAxis: "4,503,443,661 km (30.07 AU)",
//     eccentricity: "0.0086",
//     orbitalPeriod: "164.8 years",
//     synodicPeriod: "367.49 days",
//     averageSpeed: "5.43 km/s",
//     meanAnomaly: "256.228°",
//     longitudeOfAscendingNode: "131.784°",
//     argumentOfPerihelion: "273.187°",
//     satellites: "14 (incl. Triton)",
//     about: `Neptune is the eighth and farthest planet from the Sun, with a diameter of 49,244 km. Classified as an ice giant, Neptune has a composition similar to Uranus, with hydrogen, helium, and ices of water, methane, and ammonia. Its striking deep blue color is due to methane in its atmosphere. Neptune experiences the fastest winds in the Solar System, reaching speeds over 2,000 km/h, creating giant storms such as the Great Dark Spot, similar to Jupiter’s Great Red Spot. Its average temperature is around –214°C. Despite being so distant, Neptune radiates more internal heat than it receives from the Sun, which powers its dynamic weather. Neptune has a faint system of rings and 14 known moons. The largest moon, Triton, is geologically active with geysers that spew nitrogen gas, and it is thought to be a captured Kuiper Belt object. Voyager 2, which flew past Neptune in 1989, remains the only spacecraft to have visited. Neptune plays a key role in shaping the outer Solar System, influencing the orbits of objects in the Kuiper Belt. Its mysterious atmosphere and dynamic climate continue to intrigue scientists and make it a prime candidate for future exploration.`
//   },
// },
// {
//   id: 9,
//   name: "Pluto",
//   image: "/pluto.jpg",
//   menu_image: "/pluto_menu.jpg",
//   details: {
//     aphelion: "4,537,039,826 km (30.33 AU)",
//     perihelion: "4,459,753,056 km (29.81 AU)",
//     semiMajorAxis: "4,503,443,661 km (30.07 AU)",
//     eccentricity: "0.0086",
//     orbitalPeriod: "164.8 years",
//     synodicPeriod: "367.49 days",
//     averageSpeed: "5.43 km/s",
//     meanAnomaly: "256.228°",
//     longitudeOfAscendingNode: "131.784°",
//     argumentOfPerihelion: "273.187°",
//     satellites: "14 (incl. Triton)",
//     about: `Neptune is the eighth and farthest planet from the Sun, with a diameter of 49,244 km. Classified as an ice giant, Neptune has a composition similar to Uranus, with hydrogen, helium, and ices of water, methane, and ammonia. Its striking deep blue color is due to methane in its atmosphere. Neptune experiences the fastest winds in the Solar System, reaching speeds over 2,000 km/h, creating giant storms such as the Great Dark Spot, similar to Jupiter’s Great Red Spot. Its average temperature is around –214°C. Despite being so distant, Neptune radiates more internal heat than it receives from the Sun, which powers its dynamic weather. Neptune has a faint system of rings and 14 known moons. The largest moon, Triton, is geologically active with geysers that spew nitrogen gas, and it is thought to be a captured Kuiper Belt object. Voyager 2, which flew past Neptune in 1989, remains the only spacecraft to have visited. Neptune plays a key role in shaping the outer Solar System, influencing the orbits of objects in the Kuiper Belt. Its mysterious atmosphere and dynamic climate continue to intrigue scientists and make it a prime candidate for future exploration.`
//   },
// },
];

module.exports = { PlanetList };
